### ISSUE TITLE
NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long,int) with newest JDK 21-b7

### ISSUE THREAD

**Issue by ericcaspole** [renaissance-benchmarks/renaissance#370]
We are using 0.14.1.
Starting from JDK 21-b7, this exception happens related to the bug fix for  https://bugs.openjdk.org/browse/JDK-8299684

If this is fixed in Renaissance, possibly by a Spark upgrade, in newer unreleased code please let me know and we will plan for that.

java.lang.ExceptionInInitializerError
at org.apache.spark.unsafe.array.ByteArrayMethods.<clinit>(ByteArrayMethods.java:54)
at org.apache.spark.internal.config.package$.<clinit>(package.scala:1149)
at org.apache.spark.SparkConf$.<clinit>(SparkConf.scala:654)
at org.apache.spark.SparkConf.set(SparkConf.scala:94)
at org.apache.spark.SparkConf.set(SparkConf.scala:83)
at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$1(SparkSession.scala:920)
at scala.collection.mutable.HashMap$Node.foreach(HashMap.scala:627)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:489)
at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:920)
at org.renaissance.apache.spark.SparkUtil.setUpSparkContext(SparkUtil.scala:121)
at org.renaissance.apache.spark.SparkUtil.setUpSparkContext$(SparkUtil.scala:92)
at org.renaissance.apache.spark.Als.setUpSparkContext(Als.scala:43)
at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:88)
at org.renaissance.jmh.JmhRenaissanceBenchmark.setUpBenchmark(JmhRenaissanceBenchmark.java:115)
at org.renaissance.apache.spark.jmh_generated.JmhAls_runOperation_jmhTest._jmh_tryInit_f_jmhals0_G(JmhAls_runOperation_jmhTest.java:590)
at org.renaissance.apache.spark.jmh_generated.JmhAls_runOperation_jmhTest.runOperation_SingleShotTime(JmhAls_runOperation_jmhTest.java:477)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long,int)
at org.apache.spark.unsafe.Platform.<clinit>(Platform.java:113)
... 26 more
Caused by: java.lang.NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long,int)
at java.base/java.lang.Class.getConstructor0(Class.java:3685)
at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2854)
at org.apache.spark.unsafe.Platform.<clinit>(Platform.java:71)
... 26 more

**Comment by AlanBateman** [comment]
See also: https://bugs.openjdk.org/browse/JDK-8301277

**Comment by lbulej** [comment]
Spark update in Renaissance is planned. I'll check with recent JDK if it takes care of the issue.

**Comment by AlanBateman** [comment]
@lbulej Do you know if there is an issue in the Spark JIRA for this?

**Comment by lbulej** [comment]
> @lbulej Do you know if there is an issue in the Spark JIRA for this?

I did not check, sorry I can't give you a better answer ATM.

**Comment by AlanBateman** [comment]
@lbulej Spark is currently broken on JDK 20 and JDK 21 EA builds due to this hack. Do you have access to create a bug in their JIRA? Or maybe Renaissance's copy can be temporarily fixed to avoid the hack?

**Comment by lbulej** [comment]
Thanks for the update! I'm not watching Spark JIRA (or the bug trackers of all the dependencies) regularly because we usually lag behind the latest release so there is always a chance things will get fixed by updating to a newer release. In this case, I'll just make sure that the next release with substantial library updates uses fixed Spark.

**Comment by farquet** [comment]
Looks like Spark 3.5.0 addresses this problem: https://issues.apache.org/jira/browse/SPARK-42369
So technically, Renaissance 0.14.2 has a compatibility of [JDK8, JDK20].

A future release that bumps Spark version should bring the compatibility back to latest JDK.

---

Note that the removed constructor has been temporarily reinstated in the JDK but will be gone again with JDK21 GA: https://bugs.openjdk.org/browse/JDK-8303073

**Comment by AlanBateman** [comment]
It was temporarily reinstated for one build, removed again in JDK-8303083 for JDK 21 b12.

SPARK-42369 just continues the hack, it's not a proper fix to the issue. I hope they will re-visit it and remove the code that hacks into JDK internals.

**Comment by vhotspur** [comment]
I just tried adding [JDK21-ea to our CI](https://github.com/renaissance-benchmarks/renaissance/actions/runs/4551486239/jobs/8025777682?pr=379) and it seems to me the issue is still not resolved on our side. I am thus reopening this one so that we do not forget about it.

**Comment by lbulej** [comment]
> I just tried adding [JDK21-ea to our CI](https://github.com/renaissance-benchmarks/renaissance/actions/runs/4551486239/jobs/8025777682?pr=379) and it seems to me the issue is still not resolved on our side. I am thus reopening this one so that we do not forget about it.

I checked the Spark codebase and the fix is in the master branch leading to Spark 3.5 (as @farquet indicated) but not in any of the maintenance branches for Spark 3.4, 3.3, or 3.2. The Spark benchmarks will only become JDK21-compatible with Spark 3.5. In the meantime, we could limit the max JVM version for the Spark benchmarks to that we can test JDK21-ea in the CI.

**Comment by lbulej** [comment]
I have tested Renaissance using a locally built Spark 3.5.0rc3 on OpenJDK 21-b35 and it works as expected (unlike Renaissace 0.14.2), so I hope to release JDK21-compatible update soon after Spark 3.5.0.
